name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt install -y silversearcher-ag rename
      - name: Replace GxB with GzB
        run: |
          ls
          grep -i gxb CMakeLists.txt
          #ag -a -l gxb | xargs sed -i 's/GxB/GzB/g'
          rename 's/GxB/GzB/' Source/*.c
      - name: Compile
        run: |
          cd build
          cmake .. -DGBCOMPACT=1
          make -j$(nproc)
