name: Compile GzB variant
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt install -y rename
      - name: Replace GxB with GzB
        run: |
          grep --exclude-dir .git -lri GxB | xargs sed -i 's/GxB/GzB/g'
          rename 's/GxB/GzB/' Source/*.c
      - name: Compile
        run: |
          cd build
          cmake .. -DGBCOMPACT=1
          make -j$(nproc)
